# Application
spring:
  application:
    name: gomovie

  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/gomovie
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server
server:
  port: 8090

# JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: 900000

# Logging
logging:
  level:
    root: INFO
    com.gomovie: TRACE

mobi:
  fpx:
    initiate-deposit-url: ${MOBI_INITIATE_DEPOSIT_URL}
    available-banks-url: ${MOBI_AVAILABLE_BANKS_URL}
    status-check-url: ${MOBI_STATUS_CHECK_URL}

    mid: ${MOBI_MID}
    tid: ${MOBI_TID}
    sub-mid: ${MOBI_SUB_MID}
    merchant-name: ${MOBI_MERCHANT_NAME}

    moto-api-key: ${MOBI_MOTO_API_KEY}
    login-id: ${MOBI_LOGIN_ID}

    redirect-url: ${MOBI_REDIRECT_URL}